config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home" 
  get 'about', to: 'pages#about' 
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title , presence: true, length: {minimum:6, maximum:100}
    validates :description , presence: true, length: {minimum:10, maximum:300}
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  def show
    # esto es igual a que en la consola ponga article = Article.find(3) por poner un ejemplo, pero no estara
    # disponible en mi vista show.html.erb , para ello se pone el @, para convertir mi variable normal en una 
    # variable de instancia
    
  end

  def index
    @articles = Article.all 
  end

  def new
    @article = Article.new  
  end

  def edit
    # edit y update confunden algo, pero edit es de tipo get, por lo que es una vista, aqui solo renderizamos
    # segun el id que de el params, y update es tipo PUT,asi que una vez modificado un article,debe hacer render
    
  end
  

  def create
    # este comando renderiza en el navegador lo que cremos, pero mejor lo guardamos en una var pa la BD
    #render plain: params[:article]
    # @article = Article.new(params[:article]) tampoco es asi
    @article = Article.new(article_params)
    #render plain: @article.inspect aqui ya se ve como cuando en la consola creamos un articulo, con los demas fils vacios
    #@article.save

    # una vez hecho te debe redirigir al show action para mostrar el articulo que acabas de crear
    # nos vamos a routes --expanded y vemos que el prefix de show es article, entonces ese es mi path article_path
    #como la ruta es /articles/:id , levamos a pasar entre parentesis la instancia article y rails solito la va a extraer

    # redirect_to article_path(@article) esto se puede simplificar asi
    #redirect_to @article

    if @article.save
      flash[:notice] = "El articulo fue creado correctamente"
      redirect_to @article
    else
      render 'new'
    end


  end

  def update
    
    if @article.update(article_params)
      flash[:notice] = "El articulo fue actualizado correctamente"
      redirect_to @article
    else
      render 'edit'
    end
   
  end
  
  def destroy
    
    @article.destroy
    redirect_to articles_path
  end
  
  private

  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end
  
  def about 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Los siguientes errores impiden que el articulo se guarde</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
<% end %>


<%= form_with(model: @article, local: true)  do |f| %>
 <p>
   <%= f.label :title %>
   <br>
   <%= f.text_field :title %>
 </p>
 <p>
   <%= f.label :description %>
   <br>
   <%= f.text_area :description %>
 </p>
 <p>
   <%= f.submit%>
 </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form' %>

<%= link_to "Cancelar y regresar a la lista de articulos", articles_path %>

app/views/articles/index.html.erb
<h1>Pagina de listado de Articulos</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td> <%= article.title %> </td>
        <td> <%= article.description %> </td>
        <td> <%=link_to "Show", article_path(article) %> </td>
        <td> <%=link_to "Edit", edit_article_path(article) %> </td>
        <td> <%=link_to "Delete", article_path(article.id), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%=link_to "Crear nuevo articulo", new_article_path %></p>

app/views/articles/new.html.erb
<h1>Crear un nuevo Articulo</h1>

<%= render 'form' %>

<%= link_to "Regresar a la lista de articulos", articles_path %>

app/views/articles/show.html.erb
<h1>Mostrando detalles del Articulo</h1>
<%# render es un snippet para estas llaves %>
<p><strong>Title: </strong> <%= @article.title%> </p>
<p><strong>Description:  </strong> <%= @article.description%> </p>

<%# note que funcionan sin que les pase el article como parametro %>
<%= link_to "Editar", edit_article_path(@article) %> |
<%= link_to "Eliminar", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to "Regresar a la lista de articulos", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
      <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Esta es la seccion About </h1>
<%= link_to "Lista de articulos", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<h1>Esta es la ruta principal</h1>
<%= link_to "Lista de articulos", articles_path %> |
<%= link_to "About page", about_path %>